image_width: 1280
image_height: 1024
camera_name: camera_right
camera_matrix:
  rows: 3
  cols: 3
  data: [3160.6 ,    7.7   ,  353.1,
            0.0     , 3167.7,  499.2,
            0.0     ,    0.0     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.0078, 0.3867, -0.0051, -0.0286, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0,
         0, 1, 0,
         0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 3160.6,      7.7     ,    353.1,  0.0,
              0.     ,  3167.7,        499.2     , 0.0,
            0     ,      0    ,      1.     ,      0.     ]
