image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [3031.76486,    0.     ,  817.7565 ,
            0.     , 3030.89433,  477.99819,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.036956, 0.040273, -0.002454, 0.025677, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [3013.57642,    0.     ,  827.78162,    0.     ,
            0.     , 3056.71289,  476.82199,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
